### PR TITLE
Refresh the building system and the documentation

### PR DESCRIPTION
**Pull request by Ced**
Could you check this version works and compiles to your system without warning (with cmake and configure) ? This is nearly a 1.5.0 candidate (still requires a better checking system and a valcheck like other big projects).
Thanks, Ced

./autogen.sh
./configure
make
make check

### CODE REVIEW

**Comment by Lnc** [comment]
It compiles without warning on my system (with automake and CMake).
`make check` and `make test` ore ok.

**Comment by ftynse** [comment]
Try using piplibMP library from another projet with CMake, it will fail.

According to http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries#How_package_finding_works it looks for `<lower-case-name>-config.cmake` file and will ignore `piplibMP-config.cmake`

**Comment by Lnc** [comment]
Delete piplibMP-config.cmake and use piplibmp (:p)

**Comment by ftynse** [comment]
@Lnc `find_package(p piplibmp)` will fail either way;  I can resort to using piplib_gmp version, but the build system becomes self-inconsistent with piplib32 and piplib_sp, but without piplibmp for piplib_gmp.

**Comment by Lnc** [comment]
I invert old and new names :(
So, do we keep old piplibmp name (by removing commit e298072)?
Or: do we only keep piplib_sp, piplib_dp and piplib_gmp names (and remove piplib32, piplib64 and piplibmp) for CMake?

**Comment by periscop** [comment]
OK, so I guess I just need to remove the last commit and to also write
piplibmp instead of piplibMP in the makefile.am to correct the make install
problem. We can let piplib32 et al. for CMake if they help. I change the
commits in this way in a minute.

**Comment by Ced** [comment]
Well, it does not work: even after specifying cmake/piplibmp-config.cmake
in EXTRA_DIST in the Makefile.am, make install is STILL looking
for ./cmake/piplibMP-config.cmake !

libtool: install: /usr/bin/install -c .libs/pip_sp /home/bastoul/bin/pip_sp
libtool: install: /usr/bin/install -c .libs/pip_dp /home/bastoul/bin/pip_dp
libtool: install: /usr/bin/install -c .libs/pip_gmp
/home/bastoul/bin/pip_gmp
/usr/bin/install: cannot stat ‘./cmake/piplibMP-config.cmake’: No such file
or directory
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory `/home/bastoul/git/piplib'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/bastoul/git/piplib'
make: *** [install-recursive] Error 1

I guess this is something in the cmake configuration... Any suggestion
(that does not break softwares using piplibMP just to please cmake) ?

**Comment by ftynse** [comment]
Look at `configure.ac` as well https://github.com/periscop/piplib/blob/master/configure.ac#L206

**Comment by Ced** [comment]
I was writing a message about it :-D. It works by changing it, I'll drop
that pull request and do a new one based on it. Thanks,

Ced.

**Comment by Ced** [comment]
What do you think now ?
Note that I forced git pull to remove the last commit and to replace it with a new one. I'm impressed how GitHub reacted: the flow of discussion in maintained before the new commit :-) !

**Pull request merged**
